package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Observable;
import java.util.Observer;
import modelo.ClientesDB;

/**
 * Integrantes: Diana Bravo
 *              Cristian Belalcazar
 */

public class GUIEstadisticaPorSexoGrafica extends javax.swing.JFrame implements Observer{

    //Variables para la grafica de porcentajes
    private float porcentajeHombres;
    private float  porcentajeMujeres;
    private static final int ancho = 100;
    private static final int alto = 260;
    private int altoHombres;
    private int altoMujeres;
    
    /**
    * Constructor
    *
    * @param h horizontal position
    * @param v vertical position
    */
    
    public GUIEstadisticaPorSexoGrafica(int h, int v) {
        porcentajeHombres = 0;
        porcentajeMujeres = 0;
        altoHombres = 0;
        altoMujeres = 0;
        initComponents();
        setSize(460, 410);
        setLocation(h, v);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profesión:");

        myPanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(myPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstadisticaPorSexoGrafica(600, 400).setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable obs, Object arg) {
        ClientesDB cliDB = (ClientesDB) obs;
        this.setTitle("Profesión: " + cliDB.getProfesion());
        graficar(cliDB.getTotalHombres(), cliDB.getTotalMujeres());
    }
    
    private void graficar(int totalHombres, int totalMujeres)
    {
        //Total de personas, hombre y mujeres.
        int totalPersonas = totalHombres + totalMujeres;
        
        //Obtenemos los porcentajes con rexpecto a los hombres y las mujeres
        this.porcentajeHombres = (100 * ((float)(totalHombres))) / ((float)(totalPersonas));
        this.porcentajeMujeres = (100 * ((float)(totalMujeres))) / ((float)(totalPersonas));
        
        //En estas variables calculamos el porcentaje que hay que pintar en los rectangulos
        this.altoHombres = (((int)(porcentajeHombres)) * alto) / 100; 
        this.altoMujeres = (((int)(porcentajeMujeres)) * alto) / 100; 
        
        Graphics g = myPanel.getGraphics();
        //Implementamos un metodo que dibuje las graficas de porcentajes
        paintComponent(g);
     
    }
    
    //Metodo de dibujo
    @SuppressWarnings("empty-statement")
    public void paintComponent(Graphics g )
    {
        super.paintComponents(g);;
        
        g.setColor(Color.black);
        g.drawRect(60, 60, ancho, alto);
        g.drawRect(260, 60, ancho, alto);
        
        g.drawString("Hombres", 65, 345);
        g.drawString("Mujeres", 265, 345);
        g.drawString("" + porcentajeHombres +" %", 90, 55);
        g.drawString("" + porcentajeMujeres + " %", 290, 55);
       
        g.setColor(Color.RED);
        g.fillRect(61, 60 + (alto - altoHombres), ancho-1, altoHombres);
        g.fillRect(261, 60 + (alto- altoMujeres), ancho-1, altoMujeres);
    }
   
}
