package vista;

import java.util.Observable;
import java.util.Observer;
import modelo.ClientesDB;

/**
 * Integrantes: Diana Bravo
 *              Cristian Belalcazar
 */
public class GUIEstadisticaPorSexo extends javax.swing.JFrame implements Observer{

    /**
    * Constructor
    *
    * @param h horizontal position
    * @param v vertical position
    */
    public GUIEstadisticaPorSexo(int h, int v) {
        initComponents();
        setSize(400, 200);
        setLocation(h, v);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMujeres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estadística por Sexo");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Hombres:");
        jPanel1.add(jLabel1);

        txtHombres.setText("0");
        txtHombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtHombres);

        jLabel2.setText("Mujeres:");
        jPanel1.add(jLabel2);

        txtMujeres.setText("0");
        jPanel1.add(txtMujeres);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHombresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstadisticaPorSexo(400, 400).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtHombres;
    private javax.swing.JTextField txtMujeres;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable obs, Object obj) 
    {
        ClientesDB cliDB = (ClientesDB)obs;
        txtHombres.setText("" + cliDB.getTotalHombres());
        txtMujeres.setText("" + cliDB.getTotalMujeres());
        this.setTitle("Estadísticas por sexo. Profesión: " + cliDB.getProfesion());
    }
}
